---
- name: install docker-engine
  yum: name=lvm2 state=present 

#TODO : send as param / idempotency 
- name: create logical volume
  command: pvcreate /dev/xvdf

- name: create docker volume group
  command: vgcreate docker /dev/xvdf

- name: create a thin pool called thinpool
  command: lvcreate --wipesignatures y -n thinpool docker -l 95%VG

- name: create a thin pool called thinpoolmeta
  command: lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG

- name: convert the pool to thinpool
  command: lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta

- name: configure autoextension of thin pools via an lvm profile
  copy: src=./files/docker-thinpool.profile dest=/etc/lvm/profile/docker-thinpool.profile

- name: apply the new lvm profile
  command: lvchange --metadataprofile docker-thinpool docker/thinpool

- name: verify the lv is monitored.
  command: lvs -o+seg_monitor

- name: stop docker service
  service: name=docker state=stopped

- name: delete the /var/lib/docker folder
  file: path=/var/lib/docker  state=absent

- name: create the /var/lib/docker folder
  file: path=/var/lib/docker  state=touch mode=0755

- name: copy the docker daemon config file 
  copy: src=./files/daemon.json dest=/etc/docker/daemon.json

- name: daemon-reload 
  command: systemctl daemon-reload

- name: set SELINUX to permissive mode
  replace: dest=/etc/selinux/config  regexp='SELINUX=enforcing' replace='SELINUX=permissive' backup=yes

- name: add group nogroup
  group: name=nogroup state=present

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become_user: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=50
  become_user: false
#  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10

- name: start  docker service
  service: name=docker state=started
